splinec:
	g++-5 calc-bmotion.cpp -o cb.out -std=c++11 -I/media/aditya/Data/include -ggdb

crbf:
	g++-5 gencurved.cpp -o crbf.out -std=c++11 -I/media/aditya/Data/include -ggdb

convert:
	g++-5 convertDomnGmsh2.cpp -o conv.out -std=c++11 -I/media/aditya/Data/include -ggdb
